[package]
name = "server_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde_json = "1"
serde = {version = "1", features=["derive"]}
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
rayon="1.10"
csv = "1.3.1"
parking_lot = "0.12.3"